image: alpine-tox

stages:
  - build
  - test
#
# build
#
linux_autotools:
  stage: build
  tags:
    -  alpine-tox
  cache:
    # keep cache across stages
    key: "$CI_BUILD_REF_NAME/linux"
    paths:
      - cache/
  variables:
    GL_BUILD: "lin64"
  before_script:
    - autoreconf -i
    - ./configure
  script:
    - make
  artifacts:
    # keep compiled files as artifacts to pass to the test stage
    # remove them after one hour
    expire_in: 15m
    untracked: true

linux_cmake:
  stage: build
  tags:
    -  alpine-tox
  cache:
    # keep cache across stages
    key: "$CI_BUILD_REF_NAME/linux"
    paths:
      - cache/
  variables:
    GL_BUILD: "lin64"
  before_script:
    - pwd
    - mkdir -p cmake_build
    - cmake -H. -Bcmake_build -DCMAKE_COLOR_MAKEFILE=ON
  script:
    - make -C cmake_build
  artifacts:
    # keep compiled files as artifacts to pass to the test stage
    # remove them after one hour
    expire_in: 15m
    untracked: true

test:linux_autotools:
  stage: test
  when: manual
  tags:
    - alpine-tox
  cache:
    key: "$CI_BUILD_REF_NAME/linux"
    paths:
      - cache/
  dependencies:
    - linux_autotools
  script:
    - make check

.cmake_test: &cmake_test
  stage: test
  tags:
    - alpine-tox
  cache:
    key: "$CI_BUILD_REF_NAME/linux"
    paths:
      - cache/
  dependencies:
    - linux_cmake

test:version:
  <<: *cmake_test
  script:
    - cd cmake_build
    - ctest -R version

test:crypto:
  <<: *cmake_test
  script:
    - cd cmake_build
    - ctest -R crypto

test:network:
  <<: *cmake_test
  script:
    - cd cmake_build
    - ctest -R network

test:DHT:
  <<: *cmake_test
  script:
    - cd cmake_build
    - ctest -R dht

test:onion:
  <<: *cmake_test
  script:
    - cd cmake_build
    - ctest -R onion

test:messenger:
  <<: *cmake_test
  script:
    - cd cmake_build
    - ctest -R messenger

test:tox:
  <<: *cmake_test
  script:
    - cd cmake_build
    - ctest -R "tox$"

test:tox_one:
  <<: *cmake_test
  script:
    - cd cmake_build
    - ctest -R "tox_one$"
