env:
  secure: ndYANZwVcCHfmhVQEOj/BGFphqkhSzAbG+Zt6bfEGhPDfgB85IaxuU9HbxxbeCLJZheR0LYIkSO7FAu7raQnbv2diSOEW94OtBAYRDle4sq7OfENOFKk9NzCuAKGxzoe4kF+qIE35+5CEqCJKojwpSSmcvDxtpDRuxp7n70h5wg=

before_script:
 - sudo apt-get install wget

script:
  - wget -O temp https://jenkins.libtoxcore.so/job/toxic_linux_beta/build?token=$TOKEN && cat temp

notifications:
  email: false

  irc: 
    channels:
      - "chat.freenode.net#tox-groupchats"
    on_success: always
    on_failure: always
